import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import HeaderNav from "@/app/components/UI/header";
import "./globals.css"

import {Roboto} from 'next/font/google'
import Footer from "@/app/components/UI/footer";
import {layoutConfig} from "@/app/config/layout.config";

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
    variable: '--font-roboto',
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Netherlands Kitchen",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <HeaderNav/>
        <main
            className={`flex flex-col p-8 items-center justify-start w-full`}
            style={{height: `calc(100vh - ${layoutConfig.footerHeight} - ${layoutConfig.headerHeight})`}}
        >
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
